# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - wsl

  settings:
    mnd:
      ignored-functions:
        - ^os\.WriteFile
        - ^os\.MkdirAll
    tagliatelle:
      case:
        rules:
          json: goCamel
        overrides:
          - pkg: internal/discord
            rules:
              json: snake

    varnamelen:
      ignore-decls:
        - i int
        - q net/url.Values
        - q url.Values
        - ts *testscript.TestScript
        - u *url.URL
        - r *http.Request
        - re *regexp.Regexp
        - w http.ResponseWriter
        - w io.Writer

  exclusions:
    rules:
  
      # Allow "magic numbers" for parsing command-line args
      - source: if len\(args\) [><] \d+ \{
        linters:
          - mnd

      # Allow long URLs in comment lines
      - source: ^[\s]*// (See:\s*)?https://[^\s]+
        linters:
          - lll

      # Allow DAMP vs DRY in tests
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - funlen
          - goconst

      # Avoid unnecessary error checking in httptest handlers  
      - path: _test\.go
        source: w\.Write
        linters:
          - errcheck
          - gosec
      
      # Avoid overzealous error wrapping for internal tools
      - path: tools/.*\.go
        linters:
          - err113
          - wrapcheck
