# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - wsl

  settings:
    mnd:
      ignored-functions:
        - ^os\.WriteFile
        - ^os\.MkdirAll
    varnamelen:
      ignore-decls:
        - q url.Values
        - ts *testscript.TestScript
        - u *url.URL
        - w http.ResponseWriter

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - goconst
      - path: _test\.go
        source: w\.Write
        linters:
          - errcheck
          - gosec
      - path: tools/.*\.go
        linters:
          - err113
          - wrapcheck

issues:
  fix: true
