# yaml-language-server: $schema=config.schema.json
userAgent: "PatrolBot/1.0 (+https://github.com/iocalebs/patrolbot)"
wiki: "" # Env variable PATROLBOT_WIKI or flag --wiki
wikis:
  zwen:
    site:
      url: https://zeldawiki.wiki
      scriptPath: /w
      articlePath: /wiki
      rcLinkLimit: 1000
      rcMaxAgeDays: 90
    auth:
      username: PhantomCaleb@PatrolBot
      password: "" # Env variable PATROLBOT_WIKIS_ZWEN_PASSWORD
    client:
      from: phantomcalebs@gmail.com
      timeout: 10s
    reports:
      templateDir: ./templates
      types:
        weekly:
          template: weekly.tmpl
          data:
            patrolExpiring:
              windows:
                - days: 7
                - days: 14
                - days: 30
