# yaml-language-server: $schema=config.schema.json
userAgent: "PatrolBot/1.0 (+https://github.com/iocalebs/patrolbot)"
wiki: "" # Env variable PATROLBOT_WIKI or flag --wiki
wikis:
  zwen:
    site:
      url: https://zeldawiki.wiki
      scriptPath: /w
      articlePath: /wiki
    auth:
      username: PhantomCaleb@PatrolBot
      password: "" # Env variable PATROLBOT_WIKIS_ZWEN_PASSWORD
    client:
      from: phantomcalebs@gmail.com
      timeout: "10s"
