name: build

on:
  push:

permissions:
  contents: read

env:
  GO_VERSION: "1.25"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: ./.github/actions/setup-vhs
      - run: make test

  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: ./.github/actions/setup-vhs
      - run: make cover
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/profile-merged.txt
      - uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: coverage/profile-merged.txt
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v9

  e2e:
    runs-on: ubuntu-latest
    env:
      PATROLBOT_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      PATROLBOT_WIKIS_TESTWIKI_AUTH_PASSWORD: ${{ secrets.BOTPASSWORD_ZWEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make e2e
