name: release

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}
          skip_install: true
      - run: gcloud auth configure-docker ${{ vars.GOOGLE_ARTIFACT_REGISTRY_HOST }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.GOOGLE_ARTIFACT_REGISTRY_REPO_URI }}/patrolbot
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
